import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Head from 'next/head';

import nextI18nConfig from '@/../next-i18next.config.mjs';
import { MainLayout } from '@/components/common';
import { AllOrgsView } from '@/components/organizations';
import type { NextPageWithLayout } from '../_app';

const Organizations: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Organizations - Terra</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AllOrgsView />
    </>
  );
};

export default Organizations;

Organizations.getLayout = (page) => {
  return <MainLayout>{page}</MainLayout>;
};

export const getServerSideProps = async ({ locale }: { locale: string }) => ({
  props: {
    ...(await serverSideTranslations(locale, ['common', 'navigation', 'orgs'], nextI18nConfig, ['en'])),
  },
});
