import { useSession } from 'next-auth/react';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Head from 'next/head';

import nextI18nConfig from '@/../next-i18next.config.mjs';
import { Button, MainLayout } from '@/components/common';
import Link from 'next/link';
import type { NextPageWithLayout } from './_app';

const Home: NextPageWithLayout = () => {
  const { status } = useSession();

  if (status === 'unauthenticated') {
    return (
      <>
        <Head>
          <title>Welcome to Terra</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>Landing placeholder</div>
        <Link href="/auth/signin">
          <Button>Sign in</Button>
        </Link>
      </>
    );
  }

  return (
    <>
      <Head>
        <title>Home -Terra</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Home placeholder</div>
    </>
  );
};

export default Home;

Home.getLayout = (page) => {
  return <MainLayout>{page}</MainLayout>;
};

export const getServerSideProps = async ({ locale }: { locale: string }) => ({
  props: {
    ...(await serverSideTranslations(locale, ['common', 'navigation'], nextI18nConfig, ['en'])),
  },
});
